---
title: "CV"
author: "Gagarin Zhao"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<hr></hr>
### Education
<b>Columbia University Mailman School of Public Health (2020)</b>

- MPH, Department of Sociomedical Sciences
- Certificate in Applied Biostatistics
- Propective Thesis Topic: <i>Multivariate Regression Analysis of Stigma in People Living with HIV</i>
- Student leader in:
  - Students for a National Health Program ([SNaHP](http://student.pnhp.org/about/))
  - Women 4 Women
- Relevant coursework: Data Science I, Analysis of Categorical Data, Applied Regression I

<b>New York University (2017)</b>

- BA, Psychology
- Minors: Anthropology, Child & Adolescent Mental Health Studies


<hr></hr>

### Professional Experience
<b>New York City Department of Health and Mental Hygiene (June 2019 - Present)</b>

<i>College Aide, Intern Data Analyst</i>

- Utilizing SAS statistical software to analyze claims data from Medicaid and HIV data reported to the NYC DOHMH
- Assisting in conceptualizing an analysis on HIV viral suppression comparing transgender people who receive gender-affirming healthcare to non-transgender populations living with HIV
- Conducting a literature review on types of stigma that have been identified as priority areas, including HIV-related stigma, homophobia, transphobia, sexism, and racism


<b>CHAIN, Columbia University Mailman School of Public Health (January 2019 - August 2019)</b>

<i>Graduate Research Assistant</i>

- Performing quantitative data analysis and interpretation in an ongoing cohort study of persons living with HIV/AIDS in New York City and the Tri-County region, in collaboration with NYC DOHMH 
-	Writing reports and presentations that respond to the questions, interests, and priorities of the HIV Planning Council, advising policy and funding decisions, as supported by grants from the Ryan White HIV Treatment Extension Act 
- Processing systematic survey data from the perspective of persons living with HIV about their needs for health and human services, their encounters with the full continuum of HIV services, and their physical, mental and social wellbeing 

<hr></hr>

### Languages
- English, Mandarin
- SAS, R, SPSS

<hr></hr>

View a PDF version of my CV [here](Gaga_CV_oct19_github.pdf).