---
title: "Curriculum Vitae"
author: "Gagarin Zhao"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<style>
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: #59b49d;
}
</style>

### Professional Experience

<b>Louisiana Primary Care Association ([LPCA](https://www.lpca.net){target="_blank"}) (July 2020 - Present)</b>

<i>Health Information Technology (HIT) Data Analyst</i>

- I manage and develop methods for health data collection, analysis, visualizations, and reporting. I support and train community health centers to maximize their efficiency and optimize patient outcomes.

- LPCA represents 39 federally funded Community Health Center organizations across Louisiana. These organizations operate over 285 individual sites and serve over 444,000 patients a year.


<b>New York City Department of Health and Mental Hygiene, Bureau of HIV (June 2019 - December 2019)</b>

<i>College Aide, [HRTP](https://www1.nyc.gov/site/doh/about/employment/hrtp-internship.page){target="_blank"} Data Analyst</i>

- As a part of the HRTP internship program, I assisted the Bureau of HIV with analyzing Medicaid claims data and HIV surveillance data on transgender individuals and people living with HIV (PLWH). I programmed in SAS statistical software to analyze claims data from Medicaid and HIV data reported to the NYC health department. Additionally, I conceptualized an analysis on HIV viral suppression comparing transgender people who receive gender-affirming health care to non-transgender populations living with HIV.

<b>[CHAIN](https://nyhivstg.wpengine.com/nyhiv-archive/pdfs/chain/CHAIN%20Briefing%202018-1%20Location%20of%20Services.pdf){target="_blank"}, Columbia University Mailman School of Public Health (January 2019 - August 2019, January 2020 - May 2020)</b>

<i>Graduate Research Assistant</i>

- I performed quantitative data analysis and interpretation in the ongoing cohort study Community Health Advisory Information Network (C.H.A.I.N.), which aims to improve the health of persons living with HIV/AIDS in New York City and the Tri-County region in collaboration with NYC DOHMH. I also wrote reports and presentations that respond to the questions, interests, and priorities of the HIV Planning Council, advising policy and funding decisions, as supported by grants from the Ryan White HIV Treatment Extension Act.

<hr></hr>

### Education
<b>Columbia University Mailman School of Public Health</b>

- MPH, Department of Sociomedical Sciences, Advanced Certificate in Applied Biostatistics (2020)
- Master's thesis: [Predictors of Barriers to Medical Care Among People Living with HIV in New York City: Changes from 2002 to 2017](https://academiccommons.columbia.edu/doi/10.7916/d8-6zd4-mz42){target="_blank"}
- Student leader in:
  - Students for a National Health Program ([SNaHP](http://student.pnhp.org/about/){target="_blank"})
  - [Women 4 Women](https://www.instagram.com/w4w_columbia/){target="_blank"}
- Examples of coursework: Data Science I, Analysis of Categorical Data, Applied Regression I, Applied Regression II, Relational Databases & SQL Programming, Latent Variables & Structural Equations Modeling, Pharmaceutical Statistics, Statistical Programming in SAS, Dissemination & Implementation Science
- [Certified in Public Health (CPH)](https://www.nbphe.org/){target="_blank"}

<b>New York University</b>

- BA, Psychology (2017)
- Minors: Anthropology, Child & Adolescent Mental Health Studies


<hr></hr>


### Languages
- English, Mandarin Chinese
- Microsoft Access, Microsoft Excel, Microsoft PowerBI, Mplus, MySQL, R, SAS, SPSS, Tableau

<hr></hr>

### Publications and Conferences
<b>Gender-affirming surgeries are associated with high and sustained levels of viral suppression over time among transgender people with HIV in New York City, 2013-2017</b>, 23rd International AIDS Conference, July 2020

<i>Cristina Rodriguez-Hart, Gagarin Zhao, Zil Goldstein, Asa Radix, Lucia Torian</i>

<b>[Improving Data on the HIV Epidemic by Identifying Transgender Persons in Medicaid In New York City, 2013-2017](https://www.croiconference.org/abstract/improving-data-on-the-nyc-hiv-epidemic-by-identifying-transgender-people-on-medicaid/){target="_blank"}</b>, 27th Annual Conference on Retroviruses and Opportunistic Infections (CROI), March 2019

<i>Cristina Rodriguez-Hart, Beverly Obeng, Zil Goldstein, Asa Radix, Gagarin Zhao, Lucia Torian</i>

<b>[Place of Residence and Location of Services](https://nyhivprod.wpengine.com/nyhiv-archive/pdfs/chain/CHAIN%20Briefing%202018-1%20Location%20of%20Services.pdf){target="_blank"}</b>, September 2019

<i>Maiko Yomogida, Gagarin Zhao, Angela Aidala</i>

<hr></hr>

### Select Projects

<b>Trans Medicaid Project</b>

<i>Cristina Rodriguez-Hart, Gagarin Zhao, Beverly Obeng, Asa Radix, Zil Goldstein</i>

- Improving data on Medicaid data and producing analysis on health outcomes of trans PLWH in New York City

- <i>Currently in analysis manuscript stage</i>

<b>[Solo or Together? A Billboard Hot 100 Analysis of whether bands or solo careers are more successful](https://gagarinzhao.github.io/billboard_band_breakups/){target="_blank"}</b>

<i>Meeraj Kothari, Madeline Cannon, Crystal Li, Gagarin Zhao, 
Nihan Gencerliler</i>

- <i>Completion date: December 2019</i>

<hr></hr>

View a PDF version of my CV [here](gz_resume_oct20.pdf){target="_blank"} (Last updated: October 2020).