---
title: "Instacart Analysis"
navbar:
- text: "Home"
  href: index.html
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)
data("instacart")
library(plotly)
library(flexdashboard)
```

An analysis of publicly available data for Instacart, completed as a part of my MPH curriculum at Columbia University.

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A: Aisles and add to cart order on days of the week

```{r chart 1}
instacart %>%
  filter(aisle == c("energy sports drinks", "hot dogs bacon sausage", "yogurt", "coffee", "eggs")) %>% 
  mutate(Day = order_dow + 1) %>% 
  mutate(Day = lubridate::wday(Day, label = TRUE)) %>% 
  group_by(aisle, Day) %>% 
  summarize(mean_atco = 
              mean(add_to_cart_order)) %>% 
  plot_ly(x = ~Day, y = ~mean_atco, color = ~aisle, type = 'scatter', mode = 'lines') %>%  layout(title = '5 Cool Items and Average Add to Cart Order on Days of the Week',
         yaxis = list(title = 'Mean Add to Cart Order'))
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B: Frequency of orders at hours of day within produce department

```{r chart 2}
instacart %>% 
  filter(department == "produce") %>%
  group_by(order_hour_of_day, aisle) %>% 
  summarize(n = n()) %>% 
  plot_ly(
    x = ~order_hour_of_day, y = ~n, type = "bar",
    color = ~aisle) %>% 
  layout(title = 'Frequency of Ordered Items within Produce Aisles',
         xaxis = list(title = 'Hour of Day Ordered (0-24h)',
                      zeroline = TRUE,
                      range = c(0, 24)),
         yaxis = list(title = 'N',
                      zeroline = TRUE))
```

### Chart C: Distribution of add to cart order within top 10 departments

```{r chart 3}
top_dep =
  instacart %>% 
  count(department, sort = TRUE) %>% 
  top_n(10) %>% 
  select(department)

inner_join(instacart, top_dep, by = "department") %>% 
  mutate(department = fct_reorder(department, add_to_cart_order)) %>% 
  sample_n(5000) %>% 
  plot_ly(y = ~add_to_cart_order, color = ~department, type = "box",
          colors = "Set1") %>% 
  layout(title = 'Add to Cart Order within Top 10 Departments',
         xaxis = list(title = 'Department'),
         yaxis = list(title = 'Add to Cart Order',
                      zeroline = TRUE,
                      range = c(60, 0)))
```

